/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrameSingUp_In;

import java.sql.*;
import Conectores.*;
import Relaciones.*;
import java.awt.HeadlessException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Home
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        setLocationRelativeTo(null);
        cargarBD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LBL_Admin = new javax.swing.JLabel();
        LBL_CerrarSesion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        LBL_BD = new javax.swing.JLabel();
        CB_BD = new javax.swing.JComboBox<>();
        LBL_Relacion = new javax.swing.JLabel();
        CB_Relacion = new javax.swing.JComboBox<>();
        BTN_Consultar = new javax.swing.JButton();
        BTN_Eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLE_DATA = new javax.swing.JTable();
        BTN_Insertar = new javax.swing.JButton();
        BTN_Actualizar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        LBL_newUser = new javax.swing.JLabel();
        LBL_Name = new javax.swing.JLabel();
        SPT_Name = new javax.swing.JSeparator();
        TXT_Name = new javax.swing.JTextField();
        TXT_apMat = new javax.swing.JTextField();
        TXT_apPat = new javax.swing.JTextField();
        LBL_apPat = new javax.swing.JLabel();
        SPT_apPat = new javax.swing.JSeparator();
        LBL_apMat = new javax.swing.JLabel();
        SPT_apMat = new javax.swing.JSeparator();
        LBL_Correo = new javax.swing.JLabel();
        TXT_Correo = new javax.swing.JTextField();
        SPT_apPat1 = new javax.swing.JSeparator();
        LBL_PSS = new javax.swing.JLabel();
        TXT_PSS = new javax.swing.JTextField();
        SPT_apPat2 = new javax.swing.JSeparator();
        LBL_Tarjeta = new javax.swing.JLabel();
        TXT_Tarjeta = new javax.swing.JTextField();
        SPT_apPat3 = new javax.swing.JSeparator();
        LBL_CVV = new javax.swing.JLabel();
        TXT_CVV = new javax.swing.JTextField();
        SPT_apPat4 = new javax.swing.JSeparator();
        LBL_TARJETA = new javax.swing.JLabel();
        CB_TipoCard = new javax.swing.JComboBox<>();
        LBL_Name1 = new javax.swing.JLabel();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        BTN_Actualizar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        LBL_Admin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LBL_Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Admin Settings Male_30px.png"))); // NOI18N
        LBL_Admin.setText("Administrador");

        LBL_CerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LBL_CerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBL_CerrarSesion.setText("Cerrar sesión");
        LBL_CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBL_CerrarSesionMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Delete_15px_2.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBL_Admin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LBL_CerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_Admin)
                    .addComponent(LBL_CerrarSesion))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        LBL_BD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LBL_BD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Add Database_15px.png"))); // NOI18N
        LBL_BD.setText("Base de datos:");
        LBL_BD.setToolTipText("");

        CB_BD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB_BDMouseClicked(evt);
            }
        });

        LBL_Relacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LBL_Relacion.setText("Relaciones: ");
        LBL_Relacion.setToolTipText("");

        BTN_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Consultation_15px.png"))); // NOI18N
        BTN_Consultar.setText("Consultar");
        BTN_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ConsultarActionPerformed(evt);
            }
        });

        BTN_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Delete_15px_3.png"))); // NOI18N
        BTN_Eliminar.setText("Eliminar");
        BTN_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EliminarActionPerformed(evt);
            }
        });

        TABLE_DATA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TABLE_DATA.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(TABLE_DATA);

        BTN_Insertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Insert_15px.png"))); // NOI18N
        BTN_Insertar.setText("Insertar");
        BTN_Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_InsertarActionPerformed(evt);
            }
        });

        BTN_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Approve and Update_15px.png"))); // NOI18N
        BTN_Actualizar.setText("Actualizar");

        LBL_newUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LBL_newUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Plus_15px.png"))); // NOI18N
        LBL_newUser.setText("Nuevo usuario");

        LBL_Name.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        LBL_Name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Circled Female User_15px_1.png"))); // NOI18N
        LBL_Name.setText("Nombre: ");

        TXT_Name.setBackground(new java.awt.Color(204, 204, 255));
        TXT_Name.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        TXT_Name.setBorder(null);
        TXT_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_NameActionPerformed(evt);
            }
        });

        TXT_apMat.setBackground(new java.awt.Color(204, 204, 255));
        TXT_apMat.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        TXT_apMat.setBorder(null);
        TXT_apMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_apMatActionPerformed(evt);
            }
        });

        TXT_apPat.setBackground(new java.awt.Color(204, 204, 255));
        TXT_apPat.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        TXT_apPat.setBorder(null);
        TXT_apPat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_apPatActionPerformed(evt);
            }
        });

        LBL_apPat.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        LBL_apPat.setText("Apellido paterno: ");

        LBL_apMat.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        LBL_apMat.setText("Apellido materno: ");

        LBL_Correo.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        LBL_Correo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Message_15px.png"))); // NOI18N
        LBL_Correo.setText("Correo: ");

        TXT_Correo.setBackground(new java.awt.Color(204, 204, 255));
        TXT_Correo.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        TXT_Correo.setBorder(null);
        TXT_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_CorreoActionPerformed(evt);
            }
        });

        LBL_PSS.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        LBL_PSS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Password_15px_1.png"))); // NOI18N
        LBL_PSS.setText("Contraseña: ");

        TXT_PSS.setBackground(new java.awt.Color(204, 204, 255));
        TXT_PSS.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        TXT_PSS.setBorder(null);
        TXT_PSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_PSSActionPerformed(evt);
            }
        });

        LBL_Tarjeta.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        LBL_Tarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Bank Card Back Side_15px.png"))); // NOI18N
        LBL_Tarjeta.setText("Tarjeta: ");

        TXT_Tarjeta.setBackground(new java.awt.Color(204, 204, 255));
        TXT_Tarjeta.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        TXT_Tarjeta.setBorder(null);
        TXT_Tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_TarjetaActionPerformed(evt);
            }
        });
        TXT_Tarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_TarjetaKeyTyped(evt);
            }
        });

        LBL_CVV.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        LBL_CVV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Bank Card Back Side_15px.png"))); // NOI18N
        LBL_CVV.setText("CVV: ");

        TXT_CVV.setBackground(new java.awt.Color(204, 204, 255));
        TXT_CVV.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        TXT_CVV.setBorder(null);
        TXT_CVV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_CVVActionPerformed(evt);
            }
        });
        TXT_CVV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_CVVKeyTyped(evt);
            }
        });

        LBL_TARJETA.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        LBL_TARJETA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Bank Card Back Side_15px.png"))); // NOI18N
        LBL_TARJETA.setText("Tipo");

        CB_TipoCard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crédito", "Débito" }));

        LBL_Name1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        LBL_Name1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Calendar_15px.png"))); // NOI18N
        LBL_Name1.setText("Expiración: ");

        jYearChooser1.setBackground(new java.awt.Color(204, 204, 255));

        BTN_Actualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Refresh_15px.png"))); // NOI18N
        BTN_Actualizar1.setText("Refrescar");
        BTN_Actualizar1.setActionCommand("Refrescar");
        BTN_Actualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_Actualizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBL_newUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(LBL_BD)
                                .addGap(18, 18, 18)
                                .addComponent(CB_BD, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(LBL_Relacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CB_Relacion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(BTN_Consultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(LBL_Name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SPT_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXT_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(LBL_Correo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(SPT_apPat1)
                                            .addComponent(TXT_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(LBL_TARJETA)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CB_TipoCard, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(LBL_PSS)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(SPT_apPat2)
                                                    .addComponent(TXT_PSS, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(LBL_Tarjeta))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(LBL_apPat)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(TXT_apPat, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                                    .addComponent(SPT_apPat))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(LBL_apMat)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TXT_apMat)
                                                    .addComponent(SPT_apMat)))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(SPT_apPat3)
                                                    .addComponent(TXT_Tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(LBL_CVV)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(SPT_apPat4)
                                                    .addComponent(TXT_CVV, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(BTN_Actualizar1)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(LBL_Name1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(BTN_Insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_Actualizar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_BD)
                    .addComponent(CB_BD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_Relacion)
                            .addComponent(CB_Relacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_Consultar)
                            .addComponent(BTN_Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_newUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LBL_apMat)
                                    .addComponent(TXT_apMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SPT_apMat, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(LBL_Tarjeta)
                                            .addComponent(TXT_Tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SPT_apPat3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(LBL_CVV)
                                            .addComponent(TXT_CVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SPT_apPat4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(LBL_Name)
                                            .addComponent(TXT_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SPT_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(LBL_apPat)
                                            .addComponent(TXT_apPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SPT_apPat, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(LBL_Correo)
                                            .addComponent(TXT_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SPT_apPat1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(LBL_PSS)
                                            .addComponent(TXT_PSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SPT_apPat2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_TARJETA)
                            .addComponent(CB_TipoCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_Name1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMonthChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jYearChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(BTN_Actualizar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Insertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_Actualizar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void LBL_CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBL_CerrarSesionMouseClicked
        setVisible(false);
        newSession ns = new newSession();
        ns.setVisible(true);
    }//GEN-LAST:event_LBL_CerrarSesionMouseClicked

    private void TXT_apPatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_apPatActionPerformed
        // TODO add your handling code here:
        TXT_apPat.transferFocus();
    }//GEN-LAST:event_TXT_apPatActionPerformed

    private void TXT_apMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_apMatActionPerformed
        // TODO add your handling code here:
        TXT_apMat.transferFocus();
    }//GEN-LAST:event_TXT_apMatActionPerformed

    private void TXT_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_NameActionPerformed
        // TODO add your handling code here:
        TXT_Name.transferFocus();
    }//GEN-LAST:event_TXT_NameActionPerformed

    private void BTN_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EliminarActionPerformed
        // TODO add your handling code here:
        try {
            connectionMYSQL cn = new connectionMYSQL();
            Connection conexion = cn.getConnection();
            int fila = TABLE_DATA.getSelectedRow();
            String valor = TABLE_DATA.getValueAt(fila, 0).toString();
            int ID = Integer.parseInt(valor);
            deleteCliente(ID);
            consultar(CB_Relacion.getSelectedItem().toString().trim());
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_BTN_EliminarActionPerformed

    private void BTN_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ConsultarActionPerformed
        consultar(CB_Relacion.getSelectedItem().toString().trim());
    }//GEN-LAST:event_BTN_ConsultarActionPerformed

    private void CB_BDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB_BDMouseClicked
        // TODO add your handling code here:
        cargarTablas();
    }//GEN-LAST:event_CB_BDMouseClicked

    private void TXT_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_CorreoActionPerformed
        // TODO add your handling code here:
        TXT_Correo.transferFocus();
    }//GEN-LAST:event_TXT_CorreoActionPerformed

    private void TXT_PSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_PSSActionPerformed
        // TODO add your handling code here:
        TXT_PSS.transferFocus();
    }//GEN-LAST:event_TXT_PSSActionPerformed

    private void TXT_TarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_TarjetaActionPerformed
        // TODO add your handling code here:
        TXT_Tarjeta.transferFocus();
    }//GEN-LAST:event_TXT_TarjetaActionPerformed

    private void TXT_CVVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_CVVActionPerformed
        // TODO add your handling code here:
        TXT_CVV.transferFocus();
    }//GEN-LAST:event_TXT_CVVActionPerformed

    private void BTN_InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_InsertarActionPerformed
        // TODO add your handling code here:
        Cliente userA = new Cliente();
        Tarjeta cardA = new Tarjeta();
        Controlador_ClienteEmail verifyUser = new Controlador_ClienteEmail();
        Controlador_Tarjeta verifyCard = new Controlador_Tarjeta();
        connectionMYSQL cn = new connectionMYSQL();
        Connection conexion = cn.getConnection();
        
        userA.setNombre(TXT_Name.getText().toUpperCase().trim());
        userA.setA_Paterno(TXT_apPat.getText().toUpperCase().trim());
        userA.setA_Materno(TXT_apMat.getText().toUpperCase().trim());
        userA.setEmail(TXT_Correo.getText().trim());
        userA.setPassword(TXT_PSS.getText().trim());
        
        cardA.setNoTarjeta(getNoCard().trim());
        cardA.setCVV(Integer.parseInt(TXT_CVV.getText()));
        cardA.setTipo(CB_TipoCard.getSelectedItem().toString().trim());
        cardA.setFecha(getFecha().trim());
        
        if (verifyUser.verifyRegister(userA) && verifyCard.verifyCard(cardA)) 
        {
            System.out.println(userA.getNombre()+"si tiene datos");
            System.out.println(cardA.getNoTarjeta()+"si tiene tarjeta");
            verifyUser.insertar(userA, conexion, "Cliente");
            verifyCard.insertCard(cardA);
        }
    }//GEN-LAST:event_BTN_InsertarActionPerformed

    private void TXT_TarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_TarjetaKeyTyped
        // TODO add your handling code here:
        if (TXT_Tarjeta.getText().length()==16)
        {
            evt.consume();
            TXT_Tarjeta.transferFocus();
        }
    }//GEN-LAST:event_TXT_TarjetaKeyTyped

    private void TXT_CVVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_CVVKeyTyped
        // TODO add your handling code here:
        if (TXT_CVV.getText().length() == 4) 
        {
            evt.consume();
            TXT_CVV.transferFocus();
        }
    }//GEN-LAST:event_TXT_CVVKeyTyped

    private void BTN_Actualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_Actualizar1ActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_BTN_Actualizar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Actualizar;
    private javax.swing.JButton BTN_Actualizar1;
    private javax.swing.JButton BTN_Consultar;
    private javax.swing.JButton BTN_Eliminar;
    private javax.swing.JButton BTN_Insertar;
    private javax.swing.JComboBox<String> CB_BD;
    private javax.swing.JComboBox<String> CB_Relacion;
    private javax.swing.JComboBox<String> CB_TipoCard;
    private javax.swing.JLabel LBL_Admin;
    private javax.swing.JLabel LBL_BD;
    private javax.swing.JLabel LBL_CVV;
    private javax.swing.JLabel LBL_CerrarSesion;
    private javax.swing.JLabel LBL_Correo;
    private javax.swing.JLabel LBL_Name;
    private javax.swing.JLabel LBL_Name1;
    private javax.swing.JLabel LBL_PSS;
    private javax.swing.JLabel LBL_Relacion;
    private javax.swing.JLabel LBL_TARJETA;
    private javax.swing.JLabel LBL_Tarjeta;
    private javax.swing.JLabel LBL_apMat;
    private javax.swing.JLabel LBL_apPat;
    private javax.swing.JLabel LBL_newUser;
    private javax.swing.JSeparator SPT_Name;
    private javax.swing.JSeparator SPT_apMat;
    private javax.swing.JSeparator SPT_apPat;
    private javax.swing.JSeparator SPT_apPat1;
    private javax.swing.JSeparator SPT_apPat2;
    private javax.swing.JSeparator SPT_apPat3;
    private javax.swing.JSeparator SPT_apPat4;
    private javax.swing.JTable TABLE_DATA;
    private javax.swing.JTextField TXT_CVV;
    private javax.swing.JTextField TXT_Correo;
    private javax.swing.JTextField TXT_Name;
    private javax.swing.JTextField TXT_PSS;
    private javax.swing.JTextField TXT_Tarjeta;
    private javax.swing.JTextField TXT_apMat;
    private javax.swing.JTextField TXT_apPat;
    private javax.swing.JLabel jLabel2;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    // End of variables declaration//GEN-END:variables

    public void cargarBD() {
        try {
            connectionMYSQL con = new connectionMYSQL();
            try (Connection conexion = con.getConnection()) {
                Statement st = conexion.createStatement();
                ResultSet rs = st.executeQuery("SHOW DATABASES;");
                CB_BD.removeAllItems();
                while (rs.next()) {
                    CB_BD.addItem(rs.getString(1));
                }
                rs.close();
                conexion.close();
            }
        } catch (SQLException e) {
            e.getMessage();
        }
    }

    public void cargarTablas() {
        try {
            connectionMYSQL con = new connectionMYSQL();
            try (Connection conexion = con.getConnection()) {
                Statement st = conexion.createStatement();
                ResultSet rs = st.executeQuery("SHOW TABLES;");
                CB_Relacion.removeAllItems();
                while (rs.next()) {
                    CB_Relacion.addItem(rs.getString(1));
                }
                rs.close();
                conexion.close();
            }
        } catch (SQLException e) {
            e.getMessage();
        }
    }

    public void consultar(String tabla) {
        try {
            String columnas, SQL_QUERY;
            connectionMYSQL cn = new connectionMYSQL();
            Connection conexion = cn.getConnection();
            Statement st = conexion.createStatement();
            ResultSet rs = null;
            ResultSetMetaData rsmd = null;
            columnas = "DESC " + tabla;
            SQL_QUERY = "SELECT * FROM " + tabla;
            rs = st.executeQuery(SQL_QUERY);
            rsmd = rs.getMetaData();
            /*Obtener encabezado de la consulta*/
            int col = rsmd.getColumnCount();
            DefaultTableModel modelo = new DefaultTableModel();

            for (int i = 1; i <= col; i++) {
                modelo.addColumn(rsmd.getColumnLabel(i));
            }//Ciera encabezado de consulta

            while (rs.next()) {
                String filas[] = new String[col];
                for (int j = 0; j < col; j++) {
                    filas[j] = rs.getString(j + 1);
                }
                modelo.addRow(filas);
            }
            TABLE_DATA.setModel(modelo);
            rs.close();
            conexion.close();
        } catch (SQLException e) {
            e.getMessage();
        }
    }

    public void deleteCliente(int ID) {
        if (ID >= 1) {
            String SQL_DeleteEmail, SQL_DeleteData, SQL_DeleteCard, SQL_DeleteSG;
            connectionMYSQL cn = new connectionMYSQL();

            SQL_DeleteEmail = "DELETE FROM emailCliente WHERE idCliente =" + ID;
            SQL_DeleteData = "DELETE FROM cliente WHERE idCliente = " + ID;
            SQL_DeleteCard = "DELETE FROM Tarjeta WHERE idCliente ="+ID;
            SQL_DeleteSG = "DELETE FROM seguroViajero WHERE idCliente = "+ID;
            try {
                Statement st = cn.getConnection().createStatement();
                st.executeUpdate(SQL_DeleteEmail);
                st.executeUpdate(SQL_DeleteData);
                st.execute(SQL_DeleteCard);
                JOptionPane.showMessageDialog(null, "Eliminado");
            } catch (Exception e) {
                System.err.println("Error deleting user + " + ID);
                e.printStackTrace();
            }
        }

    }
    
    
    public String getNoCard() {
        String noCardF = "";
        if (TXT_Tarjeta.getText().equals("") || TXT_Tarjeta.getText().length()<16) {
            JOptionPane.showMessageDialog(null, "Numero de tarjeta no válido");
            limpiar();
        } if (TXT_Tarjeta.getText().length() == 16) 
        {
            noCardF = TXT_Tarjeta.getText().trim();
        }

        return noCardF;
    }

    public String getFecha() {
        Calendar month = new GregorianCalendar();
        int monthP = month.get(Calendar.MONTH);
        String fecha = "", mes, año;
        if ((jYearChooser1.getYear()) == 2017) {
            if (jMonthChooser1.getMonth() <= monthP) {
                JOptionPane.showMessageDialog(null, "Tarjeta expirada");
                limpiar();

            } else {
                mes = Integer.toString(jMonthChooser1.getMonth() + 1);
                año = Integer.toString(jYearChooser1.getYear());
                if ((jMonthChooser1.getMonth() + 1) >= 10) {
                    fecha = "" + año + "-" + mes + "-01";
                } else {
                    fecha = "" + año + "-0" + mes + "-01";
                }
            }
        } else if (jYearChooser1.getYear() > 2017) {
            mes = Integer.toString(jMonthChooser1.getMonth() + 1);
            año = Integer.toString(jYearChooser1.getYear());
            if ((jMonthChooser1.getMonth() + 1) >= 10) {
                fecha = "" + año + "-" + mes + "-01";
            } else {
                fecha = "" + año + "-0" + mes + "-01";
            }
        } else {
            JOptionPane.showMessageDialog(null, "Tarjeta expirada");
            limpiar();
        }
        return fecha;
    }

    
    public void limpiar()
    {
        TXT_Name.setText("");
        TXT_apPat.setText("");
        TXT_apMat.setText("");
        TXT_Correo.setText("");
        TXT_PSS.setText("");
        TXT_Tarjeta.setText("");
        TXT_CVV.setText("");
    }
}

