package FrameSingUp_In;

import Relaciones.*;
import Conectores.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/*@author Jesus Kaimorts Díaz Medina*/
public class Registro extends javax.swing.JFrame implements Tools {

    /**
     * Creates new form Home
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LBL_image = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        LBLname = new javax.swing.JLabel();
        TXTname = new javax.swing.JTextField();
        TXTap = new javax.swing.JTextField();
        TXTam = new javax.swing.JTextField();
        TXTemail = new javax.swing.JTextField();
        TXTpassword = new javax.swing.JPasswordField();
        TXT_confirmPassword = new javax.swing.JPasswordField();
        BTN_Registrar = new javax.swing.JButton();
        SPTname = new javax.swing.JSeparator();
        LBLap = new javax.swing.JLabel();
        SPTap = new javax.swing.JSeparator();
        LBLam = new javax.swing.JLabel();
        SPTam = new javax.swing.JSeparator();
        LBLemail = new javax.swing.JLabel();
        SPTemail = new javax.swing.JSeparator();
        LBLpassword = new javax.swing.JLabel();
        SPTpassword = new javax.swing.JSeparator();
        LBL_inciaSesion = new javax.swing.JLabel();
        BTN_iniciaSesion = new javax.swing.JButton();
        BTN_salir = new javax.swing.JButton();
        LBL_confirmPassword = new javax.swing.JLabel();
        SPTpassword1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBL_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AgenciaWall2.jpg"))); // NOI18N
        jPanel2.add(LBL_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 500));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 500));

        jPanel3.setBackground(new java.awt.Color(32, 33, 35));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBLname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBLname.setForeground(new java.awt.Color(57, 113, 177));
        LBLname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Name_15px.png"))); // NOI18N
        LBLname.setText("Nombre");
        jPanel3.add(LBLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        TXTname.setBackground(new java.awt.Color(32, 33, 35));
        TXTname.setForeground(new java.awt.Color(255, 255, 255));
        TXTname.setBorder(null);
        TXTname.setCaretColor(new java.awt.Color(255, 255, 255));
        TXTname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTnameActionPerformed(evt);
            }
        });
        jPanel3.add(TXTname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 210, -1));

        TXTap.setBackground(new java.awt.Color(32, 33, 35));
        TXTap.setForeground(new java.awt.Color(255, 255, 255));
        TXTap.setBorder(null);
        TXTap.setCaretColor(new java.awt.Color(255, 255, 255));
        TXTap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTapActionPerformed(evt);
            }
        });
        jPanel3.add(TXTap, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 210, -1));

        TXTam.setBackground(new java.awt.Color(32, 33, 35));
        TXTam.setForeground(new java.awt.Color(255, 255, 255));
        TXTam.setBorder(null);
        TXTam.setCaretColor(new java.awt.Color(255, 255, 255));
        TXTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTamActionPerformed(evt);
            }
        });
        jPanel3.add(TXTam, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 210, -1));

        TXTemail.setBackground(new java.awt.Color(32, 33, 35));
        TXTemail.setForeground(new java.awt.Color(255, 255, 255));
        TXTemail.setBorder(null);
        TXTemail.setCaretColor(new java.awt.Color(255, 255, 255));
        TXTemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTemailActionPerformed(evt);
            }
        });
        jPanel3.add(TXTemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 210, -1));

        TXTpassword.setBackground(new java.awt.Color(32, 33, 35));
        TXTpassword.setForeground(new java.awt.Color(255, 255, 255));
        TXTpassword.setText("jPasswordField1");
        TXTpassword.setBorder(null);
        TXTpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        TXTpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTpasswordActionPerformed(evt);
            }
        });
        jPanel3.add(TXTpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 210, -1));

        TXT_confirmPassword.setBackground(new java.awt.Color(32, 33, 35));
        TXT_confirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        TXT_confirmPassword.setText("jPasswordField1");
        TXT_confirmPassword.setBorder(null);
        TXT_confirmPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        TXT_confirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_confirmPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(TXT_confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 210, -1));

        BTN_Registrar.setBackground(new java.awt.Color(126, 67, 194));
        BTN_Registrar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        BTN_Registrar.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Registrar.setText("Registrar");
        BTN_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_RegistrarActionPerformed(evt);
            }
        });
        jPanel3.add(BTN_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 190, 40));
        jPanel3.add(SPTname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 210, 10));

        LBLap.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBLap.setForeground(new java.awt.Color(57, 113, 177));
        LBLap.setText("Apellido Paterno");
        jPanel3.add(LBLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));
        jPanel3.add(SPTap, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 210, 10));

        LBLam.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBLam.setForeground(new java.awt.Color(57, 113, 177));
        LBLam.setText("Apellido Materno");
        jPanel3.add(LBLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));
        jPanel3.add(SPTam, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 210, 10));

        LBLemail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBLemail.setForeground(new java.awt.Color(57, 113, 177));
        LBLemail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/New Post_15px_1.png"))); // NOI18N
        LBLemail.setText("Correo");
        jPanel3.add(LBLemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        jPanel3.add(SPTemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 210, 10));

        LBLpassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBLpassword.setForeground(new java.awt.Color(57, 113, 177));
        LBLpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Password_15px.png"))); // NOI18N
        LBLpassword.setText("Contraseña");
        jPanel3.add(LBLpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));
        jPanel3.add(SPTpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 210, 10));

        LBL_inciaSesion.setForeground(new java.awt.Color(57, 52, 53));
        LBL_inciaSesion.setText("Ya soy miembro, quiero ");
        jPanel3.add(LBL_inciaSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        BTN_iniciaSesion.setBackground(new java.awt.Color(126, 67, 194));
        BTN_iniciaSesion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        BTN_iniciaSesion.setForeground(new java.awt.Color(255, 255, 255));
        BTN_iniciaSesion.setText("Iniciar Sesión");
        BTN_iniciaSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_iniciaSesionActionPerformed(evt);
            }
        });
        jPanel3.add(BTN_iniciaSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 110, 30));

        BTN_salir.setBackground(new java.awt.Color(32, 33, 35));
        BTN_salir.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        BTN_salir.setForeground(new java.awt.Color(57, 113, 177));
        BTN_salir.setBorder(null);
        BTN_salir.setBorderPainted(false);
        BTN_salir.setLabel("X");
        BTN_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_salirActionPerformed(evt);
            }
        });
        jPanel3.add(BTN_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 40, -1));

        LBL_confirmPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBL_confirmPassword.setForeground(new java.awt.Color(57, 113, 177));
        LBL_confirmPassword.setText("Confirmar contraseña");
        jPanel3.add(LBL_confirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));
        jPanel3.add(SPTpassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 210, 10));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 380, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTnameActionPerformed
        TXTname.transferFocus();
    }//GEN-LAST:event_TXTnameActionPerformed

    private void TXTapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTapActionPerformed
        TXTap.transferFocus();
    }//GEN-LAST:event_TXTapActionPerformed

    private void TXTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTamActionPerformed
        TXTam.transferFocus();
    }//GEN-LAST:event_TXTamActionPerformed

    private void TXTemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTemailActionPerformed
        TXTemail.transferFocus();
    }//GEN-LAST:event_TXTemailActionPerformed

    private void BTN_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_RegistrarActionPerformed
        //Habilita los TextFields de la ventana para poder ingresar datos
        desbloquear();
        Cliente user = new Cliente();
        Controlador_ClienteEmail registro = new Controlador_ClienteEmail();
        verifyCard addCard = new verifyCard();
        
        //Inserción de los datos a los atributos del objeto Cliente
        /*Se utiliza el método toUpperCase() y trim() para establecer un formato en la 
          base de datos respecto al nombre y para evitar que haya espacios vació despues del nombre*/
        user.setNombre(TXTname.getText().toUpperCase().trim());
        user.setA_Paterno(TXTap.getText().toUpperCase().trim());
        user.setA_Materno(TXTam.getText().toUpperCase().trim());
        user.setEmail(TXTemail.getText().trim());
        user.setPassword(TXTpassword.getText().trim());
        user.setConfirmPassword(TXT_confirmPassword.getText().trim());
        
        //Verificar que los campos no estén nulos
        if (registro.verifyRegister(user)) {

            connectionMYSQL conexion = new connectionMYSQL();
            String nomTable = "Cliente";
            
            //Verifica que la contraseña sea la misma
            if ((user.getPassword()).equals(user.getConfirmPassword())) {
                
                //Realiza conexión con la Base de datos de Agencia.
                Connection conectar = conexion.getConnection();

                if (conectar != null) {
                    String url = "jdbc:mysql://localhost:3306/", nameBD = "Agencia";

                    try {
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection cn = DriverManager.getConnection(url + nameBD, "root", "root1");
                        
                        //Verifica si el cliente ya ha sido registrado con anterioridad
                        if (registro.buscarCliente_Repetido(user, conectar)) {
                            //System.out.println(""+registro.buscarCliente_Repetido(user, conectar));
                            /*Verifica si el propecto de cliente no está usando un correo ya establecido
                            en otra cuenta*/
                            if (registro.buscarCorreoRepetida(user, conectar)==false) {
                                System.out.println(""+registro.buscarCorreoRepetida(user, conectar));
                                JOptionPane.showMessageDialog(null, "Usuario previamente registrado");
                                limpiar();
                            } else {
                                //System.out.println("SOLO CUENTA YA CREADA");
                                JOptionPane.showMessageDialog(null, "CUENTA YA CREADA");
                                int res = JOptionPane.showConfirmDialog(null, "Dese usar este correo para iniciar sesión en futuros eventos",
                                                                        "AVISO", JOptionPane.YES_NO_OPTION);
                                if (res == JOptionPane.YES_OPTION) {
                                    //System.out.println("dijo si");
                                    registro.justInsertedEmail(user, conectar);
                                    reserva.VentanaReserva a = new reserva.VentanaReserva();
                                    this.setVisible(false);
                                    a.setVisible(true);
                                } else {
                                    if (res == JOptionPane.NO_OPTION) {
                                        //System.out.println("Dijo no");
                                        limpiar();
                                    }
                                }
                            }
                        } else {
                            //Realiza inserción del cliente en la Base de datos.
                            registro.insertar(user, cn, nomTable);
                            /*Bloquea cada uno de los campos (TextFields)ya ingresados.
                            */
                            //Oculta la ventana
                            this.setVisible(false);
                            //Establece un intervalo de 1 segundo antes de abrir la nueva mentana
                            Thread.sleep(1000);
                            /*Se proyecta la ventana para agregar los datos respectivos a la tarjeta
                            del usuario*/
                            addCard.setVisible(true);
                        }
                    } catch (ClassNotFoundException | SQLException ex) {
                        System.out.print(ex.getMessage());
                        System.exit(0);
                    } catch (InterruptedException ex) {
                        System.out.println(ex.getMessage());
                    }
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "Registro fallido");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Verifique su contraseña");
                TXT_confirmPassword.setText("");
            }
        }
    }//GEN-LAST:event_BTN_RegistrarActionPerformed

    private void TXTpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTpasswordActionPerformed
        TXTpassword.transferFocus();
    }//GEN-LAST:event_TXTpasswordActionPerformed

    private void BTN_iniciaSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_iniciaSesionActionPerformed
        newSession iniciaSesion = new newSession();
        this.setVisible(false);
        iniciaSesion.setVisible(true);
        

    }//GEN-LAST:event_BTN_iniciaSesionActionPerformed

    private void BTN_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BTN_salirActionPerformed

    private void TXT_confirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_confirmPasswordActionPerformed
        TXT_confirmPassword.transferFocus();
    }//GEN-LAST:event_TXT_confirmPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Registrar;
    private javax.swing.JButton BTN_iniciaSesion;
    private javax.swing.JButton BTN_salir;
    private javax.swing.JLabel LBL_confirmPassword;
    private javax.swing.JLabel LBL_image;
    private javax.swing.JLabel LBL_inciaSesion;
    private javax.swing.JLabel LBLam;
    private javax.swing.JLabel LBLap;
    private javax.swing.JLabel LBLemail;
    private javax.swing.JLabel LBLname;
    private javax.swing.JLabel LBLpassword;
    private javax.swing.JSeparator SPTam;
    private javax.swing.JSeparator SPTap;
    private javax.swing.JSeparator SPTemail;
    private javax.swing.JSeparator SPTname;
    private javax.swing.JSeparator SPTpassword;
    private javax.swing.JSeparator SPTpassword1;
    private javax.swing.JPasswordField TXT_confirmPassword;
    private javax.swing.JTextField TXTam;
    private javax.swing.JTextField TXTap;
    private javax.swing.JTextField TXTemail;
    private javax.swing.JTextField TXTname;
    private javax.swing.JPasswordField TXTpassword;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void limpiar() {
        TXTname.setText("");
        TXTap.setText("");
        TXTam.setText("");
        TXTemail.setText("");
        TXTpassword.setText("");
        TXT_confirmPassword.setText("");
    }

    @Override
    public void bloquear() {
        TXTname.setEnabled(false);
        TXTap.setEnabled(false);
        TXTam.setEnabled(false);
        TXTemail.setEnabled(false);
        TXTpassword.setEnabled(false);
        TXT_confirmPassword.setEnabled(false);
    }

    @Override
    public void desbloquear() {
        TXTname.setEnabled(true);
        TXTap.setEnabled(true);
        TXTam.setEnabled(true);
        TXTemail.setEnabled(true);
        TXTpassword.setEnabled(true);
        TXT_confirmPassword.setEnabled(true);
    }

}
