/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package FrameSingUp_In;
import Relaciones.*;
import java.sql.*;
import javax.swing.*;
import reserva.*;

/**
 *
 * @author Jesús Kaimorts Díaz Medina
 */
public class User_Profile extends javax.swing.JFrame {

    /**
     * Creates new form User_Profile
     */
    public String dd;
    String nombre, apPat, apMat, email,pss,card,cvv;
    
    public User_Profile() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void insertData(Cliente user, Connection conexion)
    {
        System.out.println(user.getEmail()+"PRUEBA1");
        System.out.println(user.getPassword()+"PRUEBA2");
        String idProfile="";
        String getID = "SELECT idCliente FROM emailCliente WHERE email like '"+user.getEmail()
                +"' AND contraseña like '"+user.getPassword()+"'";
        
        try {
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery(getID);
            while(rs.next())
            {
                idProfile = rs.getString("idCliente");
            }
            System.out.println(idProfile);
        } catch (SQLException e) { e.printStackTrace();}
        
        String getDataProfile = "SELECT nombre,apPaterno, apMaterno FROM Cliente WHERE idCliente ="+idProfile;
        String getEmailDataProfile = "SELECT email,contraseña FROM emailcliente WHERE idCliente="+idProfile;
        String getCardProfile = "SELECT numTarjeta,CVV,tipo,fechaVencimiento FROM Tarjeta WHERE idCliente =" + idProfile;
        try {
            Statement st = conexion.createStatement();
            Statement st2 = conexion.createStatement();
            Statement st3 = conexion.createStatement();
            ResultSet rs = st.executeQuery(getDataProfile);
            ResultSet rs2 = st2.executeQuery(getEmailDataProfile);
            ResultSet rs3 = st3.executeQuery(getCardProfile);
            
            while(rs.next() && rs2.next() && rs3.next())
            {
                nombre = rs.getString(1).trim();
                apPat = rs.getString(2).trim();
                apMat = rs.getString(3).trim();
                email = rs2.getString(1).trim();
                pss = rs2.getString(2).trim();    
                card = rs3.getString(1).trim();
                cvv = rs3.getString(2).trim();
            }
            
            System.out.println(nombre);
            System.out.println(apPat);
            System.out.println(apMat);
            System.out.println(email);
            System.out.println(pss);
            
            TXT_name.setText(nombre);
            TXT_email.setText(email);
            
            
        } catch (SQLException e) {
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Profile_Gral = new javax.swing.JPanel();
        SideBar = new javax.swing.JPanel();
        LBL_Home = new javax.swing.JLabel();
        LBL_CerrarSesion = new javax.swing.JLabel();
        LBL_Profile = new javax.swing.JLabel();
        LBL_Hotel = new javax.swing.JLabel();
        TXT_Hotel = new javax.swing.JTextField();
        LBL_ImageHotel = new javax.swing.JLabel();
        LBL_Buscar = new javax.swing.JLabel();
        LBL_Settings = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();
        LBL_Exit = new javax.swing.JLabel();
        LBL_Perfil_User = new javax.swing.JLabel();
        LBL_UserImage = new javax.swing.JLabel();
        SPT_User = new javax.swing.JSeparator();
        LBL_NoTarjeta = new javax.swing.JLabel();
        SPT_email = new javax.swing.JSeparator();
        LBL_Perfil_User1 = new javax.swing.JLabel();
        LBL_Contraseña = new javax.swing.JLabel();
        SPT_Contraseña = new javax.swing.JSeparator();
        SPT_Information = new javax.swing.JSeparator();
        LBL_Email1 = new javax.swing.JLabel();
        LBL_apMaterno = new javax.swing.JLabel();
        LBL_apPaterno = new javax.swing.JLabel();
        SPT_Name = new javax.swing.JSeparator();
        SPT_apPaterno = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        LBL_nombre = new javax.swing.JLabel();
        LBL_CVV = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        TXT_email = new javax.swing.JTextField();
        TXT_name = new javax.swing.JTextField();
        TXT_pss = new javax.swing.JTextField();
        TXT_apPat = new javax.swing.JTextField();
        TXT_apMat = new javax.swing.JTextField();
        TXT_Card = new javax.swing.JTextField();
        TXT_CVV = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Profile_Gral.setBackground(new java.awt.Color(0, 0, 0));

        SideBar.setBackground(new java.awt.Color(51, 51, 51));
        SideBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                SideBarMouseDragged(evt);
            }
        });
        SideBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SideBarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SideBarMouseReleased(evt);
            }
        });

        LBL_Home.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LBL_Home.setForeground(new java.awt.Color(255, 255, 255));
        LBL_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Left_15px.png"))); // NOI18N
        LBL_Home.setText("Home");
        LBL_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBL_HomeMouseClicked(evt);
            }
        });

        LBL_CerrarSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LBL_CerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        LBL_CerrarSesion.setText("Cerrar sesión");
        LBL_CerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBL_CerrarSesionMouseClicked(evt);
            }
        });

        LBL_Profile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBL_Profile.setForeground(new java.awt.Color(255, 255, 255));
        LBL_Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Menu_15px_1.png"))); // NOI18N
        LBL_Profile.setText("Perfil General");
        LBL_Profile.setIconTextGap(10);

        LBL_Hotel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBL_Hotel.setForeground(new java.awt.Color(255, 255, 255));
        LBL_Hotel.setText("Hotel");

        TXT_Hotel.setBackground(new java.awt.Color(51, 51, 51));
        TXT_Hotel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        TXT_Hotel.setForeground(new java.awt.Color(204, 204, 204));
        TXT_Hotel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        LBL_ImageHotel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LBL_ImageHotel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBL_ImageHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/5 Star Hotel_15px_1.png"))); // NOI18N

        LBL_Buscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LBL_Buscar.setForeground(new java.awt.Color(255, 255, 255));
        LBL_Buscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBL_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Search_15px_1.png"))); // NOI18N
        LBL_Buscar.setText("Buscar");
        LBL_Buscar.setIconTextGap(10);
        LBL_Buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LBL_BuscarMousePressed(evt);
            }
        });

        LBL_Settings.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LBL_Settings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBL_Settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Settings_15px.png"))); // NOI18N

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SideBarLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(LBL_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(SideBarLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(SideBarLayout.createSequentialGroup()
                                    .addComponent(LBL_Hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LBL_ImageHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(TXT_Hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideBarLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(LBL_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SideBarLayout.createSequentialGroup()
                                .addComponent(LBL_Settings, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LBL_CerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LBL_Home))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBL_Home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBL_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(LBL_ImageHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LBL_Hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXT_Hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addComponent(LBL_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LBL_Settings, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SideBarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LBL_CerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Content.setBackground(new java.awt.Color(0, 0, 0));

        LBL_Exit.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LBL_Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBL_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Delete_15px.png"))); // NOI18N
        LBL_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LBL_ExitMousePressed(evt);
            }
        });

        LBL_Perfil_User.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBL_Perfil_User.setForeground(new java.awt.Color(255, 255, 255));
        LBL_Perfil_User.setText("Perfil de usuario");
        LBL_Perfil_User.setIconTextGap(10);

        LBL_UserImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/User_50px.png"))); // NOI18N

        LBL_NoTarjeta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LBL_NoTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        LBL_NoTarjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBL_NoTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Card in Use_15px.png"))); // NOI18N
        LBL_NoTarjeta.setText("No. Tarjeta");
        LBL_NoTarjeta.setIconTextGap(10);

        LBL_Perfil_User1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LBL_Perfil_User1.setForeground(new java.awt.Color(255, 255, 255));
        LBL_Perfil_User1.setText("Información.");
        LBL_Perfil_User1.setIconTextGap(10);

        LBL_Contraseña.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LBL_Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        LBL_Contraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBL_Contraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Password_15px.png"))); // NOI18N
        LBL_Contraseña.setText("contraseña");
        LBL_Contraseña.setIconTextGap(10);

        LBL_Email1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LBL_Email1.setForeground(new java.awt.Color(255, 255, 255));
        LBL_Email1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBL_Email1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/New Post_15px_1.png"))); // NOI18N
        LBL_Email1.setText("email");
        LBL_Email1.setIconTextGap(10);

        LBL_apMaterno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LBL_apMaterno.setForeground(new java.awt.Color(255, 255, 255));
        LBL_apMaterno.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LBL_apMaterno.setText("Apellido Materno");
        LBL_apMaterno.setIconTextGap(10);

        LBL_apPaterno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LBL_apPaterno.setForeground(new java.awt.Color(255, 255, 255));
        LBL_apPaterno.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LBL_apPaterno.setText("Apellido Paterno");
        LBL_apPaterno.setIconTextGap(10);

        LBL_nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LBL_nombre.setForeground(new java.awt.Color(255, 255, 255));
        LBL_nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBL_nombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Name_15px.png"))); // NOI18N
        LBL_nombre.setText("Nombre");
        LBL_nombre.setIconTextGap(10);

        LBL_CVV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LBL_CVV.setForeground(new java.awt.Color(255, 255, 255));
        LBL_CVV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/SIM Card Chip_15px.png"))); // NOI18N
        LBL_CVV.setText("CVV");
        LBL_CVV.setIconTextGap(10);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos8/Edit Property_15px.png"))); // NOI18N
        jButton1.setText("Editar");
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(false);

        TXT_email.setEditable(false);
        TXT_email.setBackground(new java.awt.Color(0, 0, 0));
        TXT_email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXT_email.setForeground(new java.awt.Color(255, 255, 255));
        TXT_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXT_email.setBorder(null);
        TXT_email.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TXT_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_emailActionPerformed(evt);
            }
        });

        TXT_name.setEditable(false);
        TXT_name.setBackground(new java.awt.Color(0, 0, 0));
        TXT_name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXT_name.setForeground(new java.awt.Color(255, 255, 255));
        TXT_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXT_name.setBorder(null);
        TXT_name.setOpaque(false);
        TXT_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_nameActionPerformed(evt);
            }
        });

        TXT_pss.setEditable(false);
        TXT_pss.setBackground(new java.awt.Color(0, 0, 0));
        TXT_pss.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXT_pss.setForeground(new java.awt.Color(255, 255, 255));
        TXT_pss.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXT_pss.setBorder(null);

        TXT_apPat.setEditable(false);
        TXT_apPat.setBackground(new java.awt.Color(0, 0, 0));
        TXT_apPat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXT_apPat.setForeground(new java.awt.Color(255, 255, 255));
        TXT_apPat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXT_apPat.setBorder(null);

        TXT_apMat.setEditable(false);
        TXT_apMat.setBackground(new java.awt.Color(0, 0, 0));
        TXT_apMat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXT_apMat.setForeground(new java.awt.Color(255, 255, 255));
        TXT_apMat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXT_apMat.setBorder(null);

        TXT_Card.setEditable(false);
        TXT_Card.setBackground(new java.awt.Color(0, 0, 0));
        TXT_Card.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXT_Card.setForeground(new java.awt.Color(255, 255, 255));
        TXT_Card.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXT_Card.setBorder(null);

        TXT_CVV.setEditable(false);
        TXT_CVV.setBackground(new java.awt.Color(0, 0, 0));
        TXT_CVV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TXT_CVV.setForeground(new java.awt.Color(255, 255, 255));
        TXT_CVV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXT_CVV.setBorder(null);

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentLayout.createSequentialGroup()
                        .addComponent(SPT_User, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addGroup(ContentLayout.createSequentialGroup()
                        .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContentLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(LBL_UserImage)
                                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ContentLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(SPT_email, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                            .addComponent(TXT_email)))
                                    .addGroup(ContentLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(LBL_Email1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SPT_Contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                    .addComponent(LBL_Contraseña)
                                    .addComponent(TXT_pss)))
                            .addGroup(ContentLayout.createSequentialGroup()
                                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBL_Perfil_User1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LBL_Perfil_User, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LBL_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(ContentLayout.createSequentialGroup()
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentLayout.createSequentialGroup()
                        .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContentLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ContentLayout.createSequentialGroup()
                                        .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LBL_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(ContentLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(TXT_name)
                                                    .addComponent(SPT_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                                        .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(ContentLayout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(LBL_apPaterno))
                                            .addGroup(ContentLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(TXT_apPat)
                                                    .addComponent(SPT_apPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                                        .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(ContentLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(LBL_apMaterno))
                                            .addGroup(ContentLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                            .addGroup(ContentLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(TXT_apMat))))
                                    .addGroup(ContentLayout.createSequentialGroup()
                                        .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LBL_NoTarjeta)
                                            .addGroup(ContentLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(TXT_Card)
                                                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))))
                                        .addGap(28, 28, 28)
                                        .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(LBL_CVV, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                            .addComponent(jSeparator3)
                                            .addComponent(TXT_CVV)))))
                            .addGroup(ContentLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(SPT_Information, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentLayout.createSequentialGroup()
                        .addComponent(LBL_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentLayout.createSequentialGroup()
                        .addComponent(LBL_Perfil_User)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(SPT_User, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ContentLayout.createSequentialGroup()
                        .addComponent(LBL_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(TXT_pss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContentLayout.createSequentialGroup()
                        .addComponent(LBL_Email1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TXT_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LBL_UserImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SPT_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SPT_Contraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LBL_Perfil_User1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SPT_Information, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ContentLayout.createSequentialGroup()
                        .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_apPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_apMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(TXT_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TXT_apPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TXT_apMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ContentLayout.createSequentialGroup()
                        .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContentLayout.createSequentialGroup()
                                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SPT_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBL_NoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LBL_CVV, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(SPT_apPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXT_Card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TXT_CVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout Profile_GralLayout = new javax.swing.GroupLayout(Profile_Gral);
        Profile_Gral.setLayout(Profile_GralLayout);
        Profile_GralLayout.setHorizontalGroup(
            Profile_GralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Profile_GralLayout.createSequentialGroup()
                .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Profile_GralLayout.setVerticalGroup(
            Profile_GralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Profile_GralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Profile_Gral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Profile_Gral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int xy, xx;
    private void SideBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SideBarMouseDragged
         int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
        
    }//GEN-LAST:event_SideBarMouseDragged

    private void SideBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SideBarMousePressed
        setOpacity((float)0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_SideBarMousePressed

    private void SideBarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SideBarMouseReleased
        setOpacity((float)1.0);
    }//GEN-LAST:event_SideBarMouseReleased

    private void LBL_ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBL_ExitMousePressed
        System.exit(0);
    }//GEN-LAST:event_LBL_ExitMousePressed

    private void LBL_BuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBL_BuscarMousePressed
        System.out.println("Hacer una consulta");
    }//GEN-LAST:event_LBL_BuscarMousePressed

    private void TXT_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_emailActionPerformed

    private void TXT_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_nameActionPerformed

    private void LBL_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBL_HomeMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        VentanaReserva home = new VentanaReserva(TXT_email.getText(),TXT_pss.getText());
        home.setVisible(true);
    }//GEN-LAST:event_LBL_HomeMouseClicked

    private void LBL_CerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBL_CerrarSesionMouseClicked
        // TODO add your handling code here:
        setVisible(false);
        newSession ns = new newSession();
        ns.setVisible(true);
    }//GEN-LAST:event_LBL_CerrarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JLabel LBL_Buscar;
    private javax.swing.JLabel LBL_CVV;
    private javax.swing.JLabel LBL_CerrarSesion;
    private javax.swing.JLabel LBL_Contraseña;
    private javax.swing.JLabel LBL_Email1;
    private javax.swing.JLabel LBL_Exit;
    private javax.swing.JLabel LBL_Home;
    private javax.swing.JLabel LBL_Hotel;
    private javax.swing.JLabel LBL_ImageHotel;
    private javax.swing.JLabel LBL_NoTarjeta;
    private javax.swing.JLabel LBL_Perfil_User;
    private javax.swing.JLabel LBL_Perfil_User1;
    private javax.swing.JLabel LBL_Profile;
    private javax.swing.JLabel LBL_Settings;
    private javax.swing.JLabel LBL_UserImage;
    private javax.swing.JLabel LBL_apMaterno;
    private javax.swing.JLabel LBL_apPaterno;
    private javax.swing.JLabel LBL_nombre;
    private javax.swing.JPanel Profile_Gral;
    private javax.swing.JSeparator SPT_Contraseña;
    private javax.swing.JSeparator SPT_Information;
    private javax.swing.JSeparator SPT_Name;
    private javax.swing.JSeparator SPT_User;
    private javax.swing.JSeparator SPT_apPaterno;
    private javax.swing.JSeparator SPT_email;
    private javax.swing.JPanel SideBar;
    private javax.swing.JTextField TXT_CVV;
    private javax.swing.JTextField TXT_Card;
    private javax.swing.JTextField TXT_Hotel;
    private javax.swing.JTextField TXT_apMat;
    private javax.swing.JTextField TXT_apPat;
    private javax.swing.JTextField TXT_email;
    private javax.swing.JTextField TXT_name;
    private javax.swing.JTextField TXT_pss;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
    
    public void asignar(){
        
        TXT_name.setText(nombre);
        TXT_apPat.setText(apPat);
        TXT_apMat.setText(apMat);
        TXT_pss.setText(pss);
        TXT_email.setText(email);
        TXT_Card.setText(card);
        TXT_CVV.setText(cvv);
        
        System.out.println("Nombre: "+nombre);
        System.out.println("A.Pate: "+apPat);
        System.out.println("A.Mate: "+apMat);
        System.out.println("Correo: "+email);
        System.out.println("Contraseña: "+pss);
        
    }
    
    
    
    
}
