
package reserva;

import java.sql.Connection;
import java.sql.*;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static reserva.Hoteles.TXF_LUGAR_AMRESORTS;
import static reserva.cambiarImagen.contador;
import Servicios.*;



public class Home19 extends javax.swing.JFrame {
    private String nomHotel;
    private String nomRegion;
    private int costoTempA;
    private int costoTempB;
    
    public Home19() {
        
        initComponents();
        galeriaAlberca();
        this.setLocationRelativeTo(null);
    }
    
    public void setCostoTempA(int c1){
        costoTempA = c1;
    }
    
    public void setCostoTempB(int c1){
        costoTempB = c1;
    }
    
    public void setNameH(String nomH){
        nomHotel=nomH;
    }
    
    public void setRegion(String nomR){
        nomRegion=nomR;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        square = new javax.swing.JLabel();
        Box_numR = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        Box_tipoR = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        Box_opcR = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        square2 = new javax.swing.JLabel();
        costoS = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        Box_costoS = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        square3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Box_opcP = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        Exit3 = new javax.swing.JLabel();
        Exit1 = new javax.swing.JLabel();
        Exit5 = new javax.swing.JLabel();
        Exit6 = new javax.swing.JLabel();
        albecas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        sidebar.setBackground(new java.awt.Color(0, 0, 0));

        jLabel9.setBackground(new java.awt.Color(51, 51, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Circled Chevron Down_25px_1.png"))); // NOI18N
        jLabel9.setText("  Servicios :");
        jLabel9.setIconTextGap(8);
        jLabel9.setOpaque(true);

        content.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Restaurante :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Tipo:");

        square.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rounded Rectangle_12px.png"))); // NOI18N
        square.setText("jLabel1");
        square.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                squareMousePressed(evt);
            }
        });

        Box_numR.setBackground(new java.awt.Color(51, 51, 255));
        Box_numR.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Box_numR.setForeground(new java.awt.Color(255, 255, 255));
        Box_numR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        Box_numR.setOpaque(false);
        Box_numR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_numRActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Número de Personas:");

        Box_tipoR.setBackground(new java.awt.Color(51, 51, 255));
        Box_tipoR.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Box_tipoR.setForeground(new java.awt.Color(255, 255, 255));
        Box_tipoR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tradicional", "Celíacos", "Vanguardista", "Vegetariano", "Internacional" }));
        Box_tipoR.setOpaque(false);
        Box_tipoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_tipoRActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Consultar costo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        Box_opcR.setBackground(new java.awt.Color(51, 51, 255));
        Box_opcR.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Box_opcR.setForeground(new java.awt.Color(255, 255, 255));
        Box_opcR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        Box_opcR.setOpaque(false);
        Box_opcR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_opcRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(square, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Box_opcR, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Box_tipoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(Box_numR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(square)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Box_opcR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Box_tipoR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(Box_numR, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Spa :");

        square2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rounded Rectangle_12px.png"))); // NOI18N
        square2.setText("jLabel1");
        square2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                square2MousePressed(evt);
            }
        });

        costoS.setBackground(new java.awt.Color(51, 51, 255));
        costoS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        costoS.setForeground(new java.awt.Color(255, 255, 255));
        costoS.setText("Consultar costo");
        costoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoSActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        Box_costoS.setBackground(new java.awt.Color(51, 51, 255));
        Box_costoS.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Box_costoS.setForeground(new java.awt.Color(255, 255, 255));
        Box_costoS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        Box_costoS.setOpaque(false);
        Box_costoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_costoSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(costoS)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(square2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Box_costoS, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(square2)
                        .addComponent(jLabel3)
                        .addComponent(Box_costoS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(costoS)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Playa :");

        square3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rounded Rectangle_12px.png"))); // NOI18N
        square3.setText("jLabel1");
        square3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                square3MousePressed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Consultar costo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        Box_opcP.setBackground(new java.awt.Color(51, 51, 255));
        Box_opcP.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Box_opcP.setForeground(new java.awt.Color(255, 255, 255));
        Box_opcP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        Box_opcP.setOpaque(false);
        Box_opcP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_opcPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 68, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(56, 56, 56))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(square3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Box_opcP, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(square3)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Box_opcP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(21, 21, 21))
        );

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Siguiente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Exit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/More_20px.png"))); // NOI18N
        Exit3.setText("jLabel1");
        Exit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Exit3MousePressed(evt);
            }
        });

        Exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Menu_15px.png"))); // NOI18N
        Exit1.setText("jLabel1");
        Exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Exit1MousePressed(evt);
            }
        });

        Exit5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Menu_15px.png"))); // NOI18N
        Exit5.setText("jLabel1");
        Exit5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Exit5MousePressed(evt);
            }
        });

        Exit6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Menu_15px.png"))); // NOI18N
        Exit6.setText("jLabel1");
        Exit6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Exit6MousePressed(evt);
            }
        });

        albecas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Albercas/c.jpeg"))); // NOI18N

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Exit6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Exit5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(albecas)
                    .addComponent(jButton4))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentLayout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(Exit3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(787, Short.MAX_VALUE)))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit1))
                .addGap(26, 26, 26)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit5))
                .addGap(28, 28, 28)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exit6))
                .addGap(244, 244, 244))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(albecas)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentLayout.createSequentialGroup()
                    .addGap(255, 255, 255)
                    .addComponent(Exit3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(462, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sidebarLayout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        setOpacity((float)0.8);
        
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        setOpacity((float)1.0);
    }//GEN-LAST:event_formMouseReleased

    private void squareMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_squareMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_squareMousePressed

    private void Box_numRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_numRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_numRActionPerformed

    private void Box_tipoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_tipoRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_tipoRActionPerformed

    private void costoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoSActionPerformed
            //select s.costo from spa s, hotel h where h.idhotel=s.idhotel and h.nombre="RIU"
            String TH=nomHotel;
            try {      
            String sql = "select s.costo from spa s, hotel h where h.idhotel=s.idhotel and "
                    + "h.nombre='"+TH+"'"; 
            Statement st = cn.createStatement();
            String rpt2="";
            //almacena los datos de la consulta que vamosa realizar
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
            rpt2=rs.getString(1);  
            }
            JOptionPane.showMessageDialog(null, rpt2);
        } catch (SQLException ex) {
            Logger.getLogger(Home19.class.getName()).log(Level.SEVERE, null, ex);
        
        }
    }//GEN-LAST:event_costoSActionPerformed

    private void square2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_square2MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
           
            
            int i=Box_tipoR.getSelectedIndex();
            String TR="";
            if(i==0)
                TR="TRADICIONAL";
            if(i==1)
                TR="CELÍACOS";
            if(i==2)
                TR="VANGUARDISTA";
            if(i==3)
                TR="VEGETARIANO";
            if(i==4)
                TR="INTERNACIONAL";
            
            int aux=Box_numR.getSelectedIndex();
            int rpt=0;
            if(aux==0)
                rpt=1;
            if(aux==1)
                rpt=2;
            if(aux==2)
                rpt=3;
            //tipo de hotel
            String TH=nomHotel;
            String auxrpt=""+rpt;
            String sql = "Select tipo from restaurante where tipo like '%"+TR+"%'";
            String auxT = "select r.precio from restaurante r, hotel h where h.idhotel=r.idhotel "
                    + "and h.nombre like '%"+TH+"%' and r.numPersonas="+auxrpt+" and r.tipo= "
                    + "'"+TR+"'";
            Statement st = cn.createStatement();
            String rpt2="";
            //almacena los datos de la consulta que vamosa realizar
            ResultSet rs = st.executeQuery(auxT);
            while(rs.next())
            {
            rpt2=rs.getString(1);  
            }
            JOptionPane.showMessageDialog(null, rpt2);
        } catch (SQLException ex) {
            Logger.getLogger(Home19.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void square3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_square3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_square3MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            //select p.costo from playa p, hotel h where h.idhotel=p.idhotel and h.nombre="RIU"
            try {        
            String TH=nomHotel;
            String sql = "select p.costo from playa p, hotel h where h.idhotel=p.idhotel and "
                    + "h.nombre='"+TH+"'";
            Statement st = cn.createStatement();
            String rpt2="";
            //almacena los datos de la consulta que vamosa realizar
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
            rpt2=rs.getString(1);  
            }
            JOptionPane.showMessageDialog(null, rpt2);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Home19.class.getName()).log(Level.SEVERE, null, ex);
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            try {
            Generador indice = new Generador();
            int id=indice.generedCode("INFOCLIENTE");
         
             
            //insertamos un valor para la llave primaria
            PreparedStatement pstid = cn.prepareStatement("INSERT INTO infoCliente(idReservacion) VALUES (?)");
            pstid.setInt(1, id);
            pstid.executeUpdate();
            
            
            //costoSpa
            String TH=nomHotel;
            String sql1 = "select s.costo from spa s, hotel h where h.idhotel=s.idhotel and "
                    + "h.nombre='"+TH+"'";
            Statement st = cn.createStatement();
            String rpt1="";
            ResultSet rs = st.executeQuery(sql1);
            while(rs.next())
            {
            rpt1=rs.getString(1);  
            }
            int costoSpa = Integer.parseInt(rpt1);
            //////////////////////////////////////////
            //costoPlaya
            String sql2 = "select p.costo from playa p, hotel h where h.idhotel=p.idhotel and "
                    + "h.nombre='"+TH+"'";
            Statement st2 = cn.createStatement();
            String rpt2="";
            //almacena los datos de la consulta que vamosa realizar
            ResultSet rs2 = st2.executeQuery(sql2);
            while(rs2.next())
            {
            rpt2=rs2.getString(1);  
            }
            int costoPlaya = Integer.parseInt(rpt2);
            //////////////////////////////////////////tipoRestaurante, numPersonas
            int i=Box_tipoR.getSelectedIndex();
            String TR="";
            if(i==0)
                TR="TRADICIONAL";
            if(i==1)
                TR="CELÍACOS";
            if(i==2)
                TR="VANGUARDISTA";
            if(i==3)
                TR="VEGETARIANO";
            if(i==4)
                TR="INTERNACIONAL";
            
            int aux=Box_numR.getSelectedIndex();
            int rpt=0;
            if(aux==0)
                rpt=1;
            if(aux==1)
                rpt=2;
            if(aux==2)
                rpt=3;
            /////////////////////////////////////////precioRestaurante
            String auxrpt=""+rpt;
            String auxT = "select r.precio from restaurante r, hotel h where h.idhotel=r.idhotel "
                    + "and h.nombre='"+TH+"' and r.numPersonas="+auxrpt+" and r.tipo= "
                    + "'"+TR+"'";
            Statement st3 = cn.createStatement();
            String rpt3="";
            //almacena los datos de la consulta que vamosa realizar
            ResultSet rs3 = st3.executeQuery(auxT);
            while(rs3.next())
            {
            rpt3=rs3.getString(1); 
            }
            int costoRestaurante = Integer.parseInt(rpt3);
            
            /////////////////////////////////////////
            int opc1=Box_opcR.getSelectedIndex();
            int opc2=Box_costoS.getSelectedIndex();
            int opc3=Box_opcP.getSelectedIndex();
             
            String auxSpa = ""+costoSpa;    
            String auxPlaya= ""+costoPlaya;
            String auxnumPersonas=""+rpt;
            String auxPR=""+costoRestaurante;
            String auxid=""+id;
            ////////////////////////////////////////
            
            //para agregar el costo del seguroViajero
            Generador indiceO = new Generador();
            int idO=indice.generedCode("OFRECE");
            String auxidO = ""+idO;
            
            String auxSV = "select costo from seguroViajero r, where idCliente="+auxidO;
            Statement stSV = cn.createStatement();
            String rptSV="";
           
            //almacena los datos de la consulta que vamosa realizar
            ResultSet rsSV = stSV.executeQuery(auxT);
            while(rsSV.next())
            {
            rptSV=rsSV.getString(1); 
            }
            int costoSV = Integer.parseInt(rptSV);
        
            indice.UpdateCode("OFRECE");
           
            //con esto controlo el costo de temp baja/alta
            int costoTemp = costoTempA + costoTempB + costoSV;        
            
            //si desea todos los servicios
            //hacemos un update en la relacion infocliente para agregar los servicios adquiridos
            if(opc1==0&&opc2==0&&opc3==0){
            String s="update infocliente set costoSpa="+auxSpa+", costoPlaya="+auxPlaya+", "
                    + "restaurante='"+TR+"', numPersonas="+auxnumPersonas+", "
                    + "precioRestaurante="+auxPR+" WHERE idReservacion="+auxid;
            PreparedStatement pst = cn.prepareStatement(s);
            pst.executeUpdate();
            
            //hacemos un update en infocliente para sumar los costos de los servicios adquiridos
            int costoTotal=costoSpa+costoRestaurante+costoPlaya+costoTemp;
            String auxCT=""+costoTotal;
            String s2="update infocliente set costoTotal="+auxCT+" WHERE idReservacion="+auxid;
            PreparedStatement pst2 = cn.prepareStatement(s2);
            pst2.executeUpdate();
            }
            
            
            //si no desea adquirir el spa
            if(opc1==0&&opc2==1&&opc3==0){
            String s="update infocliente set costoPlaya="+auxPlaya+", "
                    + "restaurante='"+TR+"', numPersonas="+auxnumPersonas+", "
                    + "precioRestaurante="+auxPR+" WHERE idReservacion="+auxid;
            
            PreparedStatement pst = cn.prepareStatement(s);
            pst.executeUpdate();
                
            //hacemos un update en infocliente para sumar los costos de los servicios adquiridos
            int costoTotal=costoPlaya+costoRestaurante+costoTemp;
            String auxCT=""+costoTotal;
            String s2="update infocliente set costoTotal="+auxCT+" WHERE idReservacion="+auxid;
            PreparedStatement pst2 = cn.prepareStatement(s2);
            pst2.executeUpdate();
            }
            
            
            //si no desea adquirir la playa
            if(opc1==0&&opc2==0&&opc3==1){
            String s="update infocliente set costoSpa="+auxSpa+", "
                    + "restaurante='"+TR+"', numPersonas="+auxnumPersonas+", "
                    + "precioRestaurante="+auxPR+" WHERE idReservacion="+auxid;
            
            PreparedStatement pst = cn.prepareStatement(s);
            pst.executeUpdate();    
                
            //hacemos un update en infocliente para sumar los costos de los servicios adquiridos
            int costoTotal=costoSpa+costoRestaurante+costoTemp;
            String auxCT=""+costoTotal;
            String s2="update infocliente set costoTotal="+auxCT+" WHERE idReservacion="+auxid;
            PreparedStatement pst2 = cn.prepareStatement(s2);
            pst2.executeUpdate();
            }
            
            //si no desea adquirir el restaurante
            if(opc1==1&&opc2==0&&opc3==0){
            String s="update infocliente set costoSpa="+auxSpa+", costoPlaya="+auxPlaya+", "
                    + "WHERE idReservacion="+auxid;
            
            PreparedStatement pst = cn.prepareStatement(s);
            pst.executeUpdate();
            
            //hacemos un update en infocliente para sumar los costos de los servicios adquiridos
            int costoTotal=costoPlaya+costoSpa+costoTemp;
            String auxCT=""+costoTotal;
            String s2="update infocliente set costoTotal="+auxCT+" WHERE idReservacion="+auxid;
            PreparedStatement pst2 = cn.prepareStatement(s2);
            pst2.executeUpdate();
            }
            
            //si desea el restaurante pero no spa, ni playa
            if(opc1==0&&opc2==1&&opc3==1){
            String s="update infocliente set "
                    + "restaurante='"+TR+"', numPersonas="+auxnumPersonas+", "
                    + "precioRestaurante="+auxPR+" WHERE idReservacion="+auxid;
            
            PreparedStatement pst = cn.prepareStatement(s);
            pst.executeUpdate();   
            
            //hacemos un update en infocliente para sumar los costos de los servicios adquiridos
            int costoTotal=costoRestaurante+costoTemp;
            String auxCT=""+costoTotal;
            String s2="update infocliente set costoTotal="+auxCT+" WHERE idReservacion="+auxid;
            PreparedStatement pst2 = cn.prepareStatement(s2);
            pst2.executeUpdate();
            }
            
            //si desea spa, pero ni restaurante ni playa
            if(opc1==1&&opc2==0&&opc3==1){
            String s="update infocliente set costoSpa="+auxSpa+" WHERE idReservacion="+auxid;
            
            PreparedStatement pst = cn.prepareStatement(s);
            pst.executeUpdate();
            
            //hacemos un update en infocliente para sumar los costos de los servicios adquiridos
            int costoTotal=costoSpa+costoTemp;
            String auxCT=""+costoTotal;
            String s2="update infocliente set costoTotal="+auxCT+" WHERE idReservacion="+auxid;
            PreparedStatement pst2 = cn.prepareStatement(s2);
            pst2.executeUpdate();
            }
            
            //si desea playa, pero ni restaurante ni spa
            if(opc1==1&&opc2==1&&opc3==0){
            String s="update infocliente set costoPlaya="+auxPlaya+" WHERE idReservacion="+auxid;
            
            PreparedStatement pst = cn.prepareStatement(s);
            pst.executeUpdate();   
            
            //hacemos un update en infocliente para sumar los costos de los servicios adquiridos
            int costoTotal=costoPlaya+costoTemp;
            String auxCT=""+costoTotal;
            String s2="update infocliente set costoTotal="+auxCT+" WHERE idReservacion="+auxid;
            PreparedStatement pst2 = cn.prepareStatement(s2);
            pst2.executeUpdate();
            }
            
            //hacemos un update en costoTotal de infocliente por si no desea adquirir ninguno de 
            //los servicios adicionales
            if(opc1==1&&opc2==1&&opc3==1){
            int costoTotal=costoTemp;
            String auxCT=""+costoTotal;
            String s="update infocliente set costoTotal="+auxCT+" WHERE idReservacion="+auxid;
            PreparedStatement pst = cn.prepareStatement(s);
            pst.executeUpdate();
            }
            
            //AGREGAMOS EL ATRIBUTO DE nombreHotelRegion
            String s2="update infocliente set nombreHotelRegion='"+nomHotel+" "+nomRegion+"' "
                    + "WHERE idReservacion="+auxid;
            
            PreparedStatement pste = cn.prepareStatement(s2);
            pste.executeUpdate();
    
            //actualizamos el índice
            indice.UpdateCode("INFOCLIENTE");
                
            //System.exit(0);
            Servicios.MedioTransporte go = new Servicios.MedioTransporte();
                setVisible(false);
                go.setVisible(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(Home19.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Exit3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Exit3MousePressed

    private void Exit5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Exit5MousePressed

    private void Exit6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Exit6MousePressed

    private void Exit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Exit1MousePressed

    private void Box_costoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_costoSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_costoSActionPerformed

    private void Box_opcRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_opcRActionPerformed
        
    }//GEN-LAST:event_Box_opcRActionPerformed

    private void Box_opcPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_opcPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_opcPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home19.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Home19().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Box_costoS;
    private javax.swing.JComboBox<String> Box_numR;
    private javax.swing.JComboBox<String> Box_opcP;
    private javax.swing.JComboBox<String> Box_opcR;
    private javax.swing.JComboBox<String> Box_tipoR;
    private javax.swing.JLabel Exit1;
    private javax.swing.JLabel Exit3;
    private javax.swing.JLabel Exit5;
    private javax.swing.JLabel Exit6;
    public javax.swing.JLabel albecas;
    private javax.swing.JPanel content;
    private javax.swing.JButton costoS;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel square;
    private javax.swing.JLabel square2;
    private javax.swing.JLabel square3;
    // End of variables declaration//GEN-END:variables
    ConexionSQL co = new ConexionSQL();
    Connection cn = co.getConnection();
    
    public void galeriaAlberca()
    {
        int velocidad = 3;
        
        Timer timer;
        TimerTask tarea;
        int velmil = velocidad*1000;        
        
        tarea = new TimerTask(){
            int contador=0;
            @Override
            public void run() {
                Icon icono;
                
                switch(contador)
                {
                    case 0: 
                        contador = 1;
                        icono = new ImageIcon(getClass().getResource("/Albercas/b.jpeg"));
                        albecas.setIcon(icono);
                        break;
                    case 1:
                        contador = 2;
                        icono = new ImageIcon(getClass().getResource("/Albercas/c.jpeg"));
                        albecas.setIcon(icono);
                        break;
                    case 2: 
                        contador = 3;
                        icono = new ImageIcon(getClass().getResource("/Albercas/c.jpeg"));
                        albecas.setIcon(icono);
                        break;
                    case 3: 
                        contador = 4;
                        icono = new ImageIcon(getClass().getResource("/Albercas/d.jpeg"));
                        albecas.setIcon(icono);
                        break;
                    case 4: 
                        contador = 5;
                        icono = new ImageIcon(getClass().getResource("/Albercas/e.jpeg"));
                        albecas.setIcon(icono);
                        break;
                    case 5:
                        contador = 0;
                        icono = new ImageIcon(getClass().getResource("/Albercas/f.jpeg"));
                        albecas.setIcon(icono);
                        break;
                    
                }
            }
            
        };
        
        timer = new Timer();
        
        timer.scheduleAtFixedRate(tarea, velmil, velmil);
    }
    
}
