-- MySQL Script generated by MySQL Workbench
-- 02/24/17 10:02:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sams
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sams
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sams` DEFAULT CHARACTER SET utf8 ;
USE `sams` ;

-- -----------------------------------------------------
-- Table `sams`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sams`.`estado` (
  `idEdo` INT(11) NOT NULL,
  `estado` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idEdo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sams`.`club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sams`.`club` (
  `idClub` INT(10) UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  `tel` VARCHAR(60) NULL DEFAULT NULL,
  `idEdo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idClub`),
  INDEX `idEdo` (`idEdo` ASC),
  CONSTRAINT `club_ibfk_1`
    FOREIGN KEY (`idEdo`)
    REFERENCES `sams`.`estado` (`idEdo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sams`.`socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sams`.`socio` (
  `idSocio` INT(10) UNSIGNED NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idSocio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sams`.`emailsocio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sams`.`emailsocio` (
  `idSocio` INT(10) UNSIGNED NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idSocio`, `email`),
  CONSTRAINT `emailsocio_ibfk_1`
    FOREIGN KEY (`idSocio`)
    REFERENCES `sams`.`socio` (`idSocio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sams`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sams`.`empleado` (
  `idGerente` INT(10) UNSIGNED NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `idClub` INT(10) UNSIGNED NULL DEFAULT NULL,
  `salario` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idGerente`, `nombre`),
  INDEX `idClub` (`idClub` ASC),
  CONSTRAINT `empleado_ibfk_1`
    FOREIGN KEY (`idClub`)
    REFERENCES `sams`.`club` (`idClub`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sams`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sams`.`producto` (
  `idProducto` INT(10) UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `idProveedor` INT(10) UNSIGNED NOT NULL,
  `precioUnitario` DOUBLE NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `FK_producto_1` (`idProveedor` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sams`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sams`.`proveedor` (
  `idProveedor` INT(10) UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sams`.`proveedorsams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sams`.`proveedorsams` (
  `idClub` INT(10) UNSIGNED NOT NULL,
  `idProveedor` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idClub`, `idProveedor`),
  INDEX `FK_proveedorsams_2` (`idProveedor` ASC),
  INDEX `idProveedor` (`idProveedor` ASC),
  CONSTRAINT `proveedorsams_ibfk_1`
    FOREIGN KEY (`idClub`)
    REFERENCES `sams`.`club` (`idClub`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `proveedorsams_ibfk_2`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `sams`.`proveedor` (`idProveedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sams`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sams`.`servicio` (
  `idServicio` INT(11) NOT NULL,
  `nombre` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`idServicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sams`.`servicioclub`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sams`.`servicioclub` (
  `idServicio` INT(11) NULL DEFAULT NULL,
  `idClub` INT(10) UNSIGNED NULL DEFAULT NULL,
  INDEX `idServicio` (`idServicio` ASC),
  INDEX `idClub` (`idClub` ASC),
  CONSTRAINT `servicioclub_ibfk_1`
    FOREIGN KEY (`idServicio`)
    REFERENCES `sams`.`servicio` (`idServicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `servicioclub_ibfk_2`
    FOREIGN KEY (`idClub`)
    REFERENCES `sams`.`club` (`idClub`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sams`.`socioclub`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sams`.`socioclub` (
  `idSocio` INT(10) UNSIGNED NOT NULL,
  `idClub` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idSocio`, `idClub`),
  INDEX `FK_sociosams_1` (`idClub` ASC),
  CONSTRAINT `socioclub_ibfk_1`
    FOREIGN KEY (`idSocio`)
    REFERENCES `sams`.`socio` (`idSocio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `socioclub_ibfk_2`
    FOREIGN KEY (`idClub`)
    REFERENCES `sams`.`club` (`idClub`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
